all: executa_essa_merda

executa_essa_merda: listaseq.o listaseqmain.o
	gcc -o executa_essa_merda listaseq.o listaseqmain.o

listaseq.o: listaseq.c
	gcc -c lista_v.c

listaseqmain.o: listaseqmain.c
	gcc -c listaseqmain.c 
